### ISSUE TITLE
unable to reproduce results

### ISSUE THREAD

**Issue by albertma-evotec** [coleygroup/molpal#14]
Hi, I am trying to reproduce your Enamine 50k results yet unsuccessful. I was using the provided Enamine50k_online.ini config file in examples/config folder. No settings were changed except the output-dir name, I chose a different name.
![image](https://user-images.githubusercontent.com/54853041/144327490-bfd1901d-521d-4b61-ab0a-f1e362879927.png)

These are the three things generated in the directory after the run is completed.
![image](https://user-images.githubusercontent.com/54853041/144326396-f1791708-428e-48ca-a89e-49a3aaf58166.png)

in the data folder, there are:
![image](https://user-images.githubusercontent.com/54853041/144326746-8a8f4517-c847-4262-875c-cfd841378e9e.png)

I tried to analyze these explored compounds to calculate how well they recover the top-500 scored compounds. It only achieve the 'random' performance. Is there any thing I missed?
![image](https://user-images.githubusercontent.com/54853041/144327362-d25a13a6-413d-4535-8646-5bf1bffb74c9.png)

Thanks

**Comment by davidegraff** [comment]
Can you share what the output config file contains and how you’re performing the analysis?

**Comment by albertma-evotec** [comment]
This is the generated config.ini I mentioned above.

![image](https://user-images.githubusercontent.com/54853041/144401787-3984c4e5-b04a-4659-91cf-18b120d40821.png)

These are what inside the chkpts folder:

![image](https://user-images.githubusercontent.com/54853041/144402150-4fa7a5db-0d8a-4136-9ec1-1153648f702c.png)
![image](https://user-images.githubusercontent.com/54853041/144404480-ca8751bf-64b2-40c7-b4b9-59f53d221347.png)

None of the generated files and folders have the structures of what mentioned in the README, so I cannot really follow 'Analyzing data' section.

![image](https://user-images.githubusercontent.com/54853041/144402824-90513a68-0d04-49db-82a4-0a8d34914df6.png)

So I simply retrieve the top 500 scored compounds from the below file which is the same file used for objective look up and then check against the generated top_????_explored_iter_?.csv files to see how many top 500 compounds are recovered by the explored sets.

![image](https://user-images.githubusercontent.com/54853041/144403992-91f2b8f1-425f-4c52-88f5-ae49942e29d1.png)

**Comment by davidegraff** [comment]
You didn’t specify your acquisition metric, so it used the default random metric. That’s why you’re observing the same results as random acquisition

**Comment by albertma-evotec** [comment]
Ok thanks, I thought it was greedy by default when I look at the minimal_config.ini 
![image](https://user-images.githubusercontent.com/54853041/144422310-ec0018ca-1f7e-471e-bf4d-c6c32cd89ba0.png)

**Comment by davidegraff** [comment]
Oh fair point. I’ll fix the documentation for this
