### ISSUE TITLE
docking for objectives

### ISSUE THREAD

**Issue by fdaqin-v** [coleygroup/molpal#17]
Great work！
Currently, I have a problem like this. In the example of Enamine50k, I just change the objective type from lookup to docking in the Enamine50k_retrain.ini, and I also updated the docking.ini file (4nuu, center = [6.69, 17.69, -7.07], size = [40, 40, 40]).However, it seems that the docking does not work properly. I saw someone asked a similar question, but I don’t know how to deal with it, thank you！

(prepare_and_run pid=201507) Information (optional):
(prepare_and_run pid=201507)   --help                     display usage summary
(prepare_and_run pid=201507)   --help_advanced            display usage summary with advanced options
(prepare_and_run pid=201507)   --version                  display program version
(prepare_and_run pid=201507) 
(prepare_and_run pid=201507) 
Docking: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 503/503 [00:08<00:00, 59.15ligand/s]
Exception raised! Intemediate state saved to "molpal_50k/chkpts/iter_0_2021-12-21_18-02-39/state.json"
Traceback (most recent call last):
  File "run.py", line 71, in <module>
    main()
  File "run.py", line 55, in main
    explorer.run()
  File "/home/fgq/molpal-main/molpal/explorer.py", line 317, in run
    self.explore_initial()
  File "/home/fgq/molpal-main/molpal/explorer.py", line 363, in explore_initial
    self.write_scores(include_failed=True)
  File "/home/fgq/molpal-main/molpal/explorer.py", line 542, in write_scores
    top_m = self.top_explored(m)
  File "/home/fgq/molpal-main/molpal/explorer.py", line 473, in top_explored
    if k / len(self.scores) < 0.8:
ZeroDivisionError: division by zero
(prepare_and_run pid=201492) ERROR: docking failed. Message: Command line parse error: unrecognised option '--log=/tmp/pyscreener/session_2021-12-21_18-02-29/outputs/vina_4unn_receptor_ligand_493_0.log'
(prepare_and_run pid=201492) 
(prepare_and_run pid=201492) Correct usage:
(prepare_and_run pid=201492) 
(prepare_and_run pid=201492) Input:
(prepare_and_run pid=201492)   --receptor arg             rigid part of the receptor (PDBQT)
(prepare_and_run pid=201492)   --flex arg                 flexible side chains, if any (PDBQT)
(prepare_and_run pid=201492)   --ligand arg               ligand (PDBQT)
(prepare_and_run pid=201492)   --batch arg                batch ligand (PDBQT)
(prepare_and_run pid=201492)   --scoring arg (=vina)      scoring function (ad4, vina or vinardo)

**Comment by fdaqin-v** [comment]
vina_1.2.3_linux_x86_64

**Comment by davidegraff** [comment]
Pyscreener is designed to work with vina 1.1.2

**Comment by fdaqin-v** [comment]
OK, thanks! I will try again.

**Comment by fdaqin-v** [comment]
Vina version was chenged to 1.1.2 (vina_1.1.2-boost-new_linux_x86_64), and it really works for me. Thanks very much!

---------------------------------------------
ITER: 5/5 | TOP-105 AVE: -4.920 | BUDGET: 530/10560. Continuing...
Inference: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.91smi/s]
Docking:   0%|                                                                                                                                                                         | 0/106 [00:00<?, ?ligand/s](prepare_and_run pid=267840) ERROR: docking failed. Message: 
(prepare_and_run pid=267840) 
(prepare_and_run pid=267840) Parse error on line 106 in file "/tmp/pyscreener/session_2021-12-22_09-21-27/inputs/ligand_532_0.pdbqt": Unknown or inappropriate tag
(prepare_and_run pid=267840) 
Docking:  21%|█████████████████████████████████▏                                                                                                                              | 22/106 [01:46<06:47,  4.85s/ligand](prepare_and_run pid=267866) ERROR: docking failed. Message: 
(prepare_and_run pid=267866) 
(prepare_and_run pid=267866) Parse error on line 113 in file "/tmp/pyscreener/session_2021-12-22_09-21-27/inputs/ligand_565_0.pdbqt": Unknown or inappropriate tag
(prepare_and_run pid=267866) 
Docking: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 106/106 [06:15<00:00,  3.55s/ligand]
Finished exploring!
FINAL TOP-105 AVE: -4.910 | FINAL BUDGET: 636/10560.
Final averages
--------------
TOP-0.01%: -4.000
TOP-0.05%: -4.160
TOP-0.10%: -4.280
TOP-0.50%: -4.698
Total time for exploration: 0d 0h 37m 37.68s
Thanks for using MolPAL!

**Comment by fdaqin-v** [comment]
Vina version was chenged to 1.1.2 (vina_1.1.2-boost-new_linux_x86_64), and it really works for me. Thanks very much!


ITER: 5/5 | TOP-105 AVE: -4.920 | BUDGET: 530/10560. Continuing...
Inference: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.91smi/s]
Docking:   0%|                                                                                                                                                                         | 0/106 [00:00<?, ?ligand/s](prepare_and_run pid=267840) ERROR: docking failed. Message: 
(prepare_and_run pid=267840) 
(prepare_and_run pid=267840) Parse error on line 106 in file "/tmp/pyscreener/session_2021-12-22_09-21-27/inputs/ligand_532_0.pdbqt": Unknown or inappropriate tag
(prepare_and_run pid=267840) 
Docking:  21%|█████████████████████████████████▏                                                                                                                              | 22/106 [01:46<06:47,  4.85s/ligand](prepare_and_run pid=267866) ERROR: docking failed. Message: 
(prepare_and_run pid=267866) 
(prepare_and_run pid=267866) Parse error on line 113 in file "/tmp/pyscreener/session_2021-12-22_09-21-27/inputs/ligand_565_0.pdbqt": Unknown or inappropriate tag
(prepare_and_run pid=267866) 
Docking: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 106/106 [06:15<00:00,  3.55s/ligand]
Finished exploring!
FINAL TOP-105 AVE: -4.910 | FINAL BUDGET: 636/10560.
Final averages
--------------
TOP-0.01%: -4.000
TOP-0.05%: -4.160
TOP-0.10%: -4.280
TOP-0.50%: -4.698
Total time for exploration: 0d 0h 37m 37.68s
Thanks for using MolPAL!

**Comment by fdaqin-v** [comment]
Vina version was changed to 1.1.2(vina_1.1.2-boost-new_linux_x86_64), and  it really works for me. Thanks very much!

-------------------------------------------
ITER: 5/5 | TOP-105 AVE: -4.920 | BUDGET: 530/10560. Continuing...
Inference: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.91smi/s]
Docking:   0%|                                                                                                                                                                         | 0/106 [00:00<?, ?ligand/s](prepare_and_run pid=267840) ERROR: docking failed. Message: 
(prepare_and_run pid=267840) 
(prepare_and_run pid=267840) Parse error on line 106 in file "/tmp/pyscreener/session_2021-12-22_09-21-27/inputs/ligand_532_0.pdbqt": Unknown or inappropriate tag
(prepare_and_run pid=267840) 
Docking:  21%|█████████████████████████████████▏                                                                                                                              | 22/106 [01:46<06:47,  4.85s/ligand](prepare_and_run pid=267866) ERROR: docking failed. Message: 
(prepare_and_run pid=267866) 
(prepare_and_run pid=267866) Parse error on line 113 in file "/tmp/pyscreener/session_2021-12-22_09-21-27/inputs/ligand_565_0.pdbqt": Unknown or inappropriate tag
(prepare_and_run pid=267866) 
Docking: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 106/106 [06:15<00:00,  3.55s/ligand]
Finished exploring!
FINAL TOP-105 AVE: -4.910 | FINAL BUDGET: 636/10560.
Final averages
--------------
TOP-0.01%: -4.000
TOP-0.05%: -4.160
TOP-0.10%: -4.280
TOP-0.50%: -4.698
Total time for exploration: 0d 0h 37m 37.68s
Thanks for using MolPAL!

**Comment by fdaqin-v** [comment]
Vina version was changed to 1.1.2(vina_1.1.2-boost-new_linux_x86_64), and it really works for me. Thanks very much!

ITER: 5/5 | TOP-105 AVE: -4.920 | BUDGET: 530/10560. Continuing...
Inference: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.91smi/s]
Docking:   0%|                                                                                                                                                                         | 0/106 [00:00<?, ?ligand/s](prepare_and_run pid=267840) ERROR: docking failed. Message: 
(prepare_and_run pid=267840) 
(prepare_and_run pid=267840) Parse error on line 106 in file "/tmp/pyscreener/session_2021-12-22_09-21-27/inputs/ligand_532_0.pdbqt": Unknown or inappropriate tag
(prepare_and_run pid=267840) 
Docking:  21%|█████████████████████████████████▏                                                                                                                              | 22/106 [01:46<06:47,  4.85s/ligand](prepare_and_run pid=267866) ERROR: docking failed. Message: 
(prepare_and_run pid=267866) 
(prepare_and_run pid=267866) Parse error on line 113 in file "/tmp/pyscreener/session_2021-12-22_09-21-27/inputs/ligand_565_0.pdbqt": Unknown or inappropriate tag
(prepare_and_run pid=267866) 
Docking: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 106/106 [06:15<00:00,  3.55s/ligand]
Finished exploring!
FINAL TOP-105 AVE: -4.910 | FINAL BUDGET: 636/10560.
Final averages
--------------
TOP-0.01%: -4.000
TOP-0.05%: -4.160
TOP-0.10%: -4.280
TOP-0.50%: -4.698
Total time for exploration: 0d 0h 37m 37.68s
Thanks for using MolPAL!

**Comment by fdaqin-v** [comment]
Vina version was changed to 1.1.2(vina_1.1.2-boost-new_linux_x86_64), and it really works for me. Thanks very much!


ITER: 5/5 | TOP-105 AVE: -4.920 | BUDGET: 530/10560. Continuing...
Inference: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.91smi/s]
Docking:   0%|                                                                                                                                                                         | 0/106 [00:00<?, ?ligand/s](prepare_and_run pid=267840) ERROR: docking failed. Message: 
(prepare_and_run pid=267840) 
(prepare_and_run pid=267840) Parse error on line 106 in file "/tmp/pyscreener/session_2021-12-22_09-21-27/inputs/ligand_532_0.pdbqt": Unknown or inappropriate tag
(prepare_and_run pid=267840) 
Docking:  21%|█████████████████████████████████▏                                                                                                                              | 22/106 [01:46<06:47,  4.85s/ligand](prepare_and_run pid=267866) ERROR: docking failed. Message: 
(prepare_and_run pid=267866) 
(prepare_and_run pid=267866) Parse error on line 113 in file "/tmp/pyscreener/session_2021-12-22_09-21-27/inputs/ligand_565_0.pdbqt": Unknown or inappropriate tag
(prepare_and_run pid=267866) 
Docking: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 106/106 [06:15<00:00,  3.55s/ligand]
Finished exploring!
FINAL TOP-105 AVE: -4.910 | FINAL BUDGET: 636/10560.
Final averages

TOP-0.01%: -4.000
TOP-0.05%: -4.160
TOP-0.10%: -4.280
TOP-0.50%: -4.698
Total time for exploration: 0d 0h 37m 37.68s
Thanks for using MolPAL!

**Comment by davidegraff** [comment]
Glad to see it’s working! Remember to add the —minimize flag to your docking objective config so that you can identify the best docking scores

**Comment by fdaqin-v** [comment]
Thanks! I will check this option.
