### ISSUE TITLE
Question for command

### ISSUE THREAD

**Issue by rebirthjin** [coleygroup/molpal#3]
Hi!
I'm very interesting your program!

Is it possible to run the docking and lookup objective simultaneously?
command like: 

python run.py --objective docking .... --objective lookup ....

Thank you for sharing.

**Comment by davidegraff** [comment]
Hello!

i believe you’re talking about multi-objective optimization. Unfortunately, we don’t currently support this but we plan to implement it in a future update!

**Comment by rebirthjin** [comment]
@davidegraff
Thanks for kind response.
I wonder that molpal provides an iterative optimization by docking and model at same time.
I appreciate your great jobs!
