### ISSUE TITLE
what's your take on random sampling?

### ISSUE THREAD

**Issue by likun1212** [coleygroup/molpal#30]
Hi,

In molpal you used Bayesian optimization to do sampling.

however, in some other approaches that just use random sampling, and achieved good results. for instance, 

1) Gentile F, Agrawal V, Hsing M, et al. Deep docking: a deep learning platform for augmentation of structure based drug discovery[J]. ACS central science, 2020, 6(6): 939-949.

2) Martin L. State of the art iterative docking with logistic regression and Morgan fingerprints[J]. 2021.

could you please have some comments on that? is BO a necessary？

**Comment by davidegraff** [comment]
Those approaches don’t do random sampling. We included a random sampling baseline comparison in our paper, so if you’re curious I’d recommend looking there
