### ISSUE TITLE
[QUESTION]: Are docking scores for 2.1 million member HTS Collection (“Enamine HTS”) against 4UNN PBB available?

### ISSUE THREAD

**Issue by JSLJ23** [coleygroup/molpal#42]
**What are you trying to do?**
Requesting for some data from MolPal publication.

Hi Molpal developers,

I was wondering if from your paper, are the docking scores for the 2.1 million member HTS Collection (“Enamine HTS”) docked with Autodock Vina against 4UNN PBB available?
I was hoping to try and reproduce the results in an adaptation of this active learning apporach and it would be really helpful if these were available to compute the metrics that Figures 1, 2 & 3 displayed in the MolPal paper.

Thank you.

Best regards,
Joshua Soon

**Comment by davidegraff** [comment]
they're available [here](https://github.com/coleygroup/molpal/blob/main/data/EnamineHTS_scores.csv.gz)

**Comment by JSLJ23** [comment]
Ok thank you very much!
A couple of quick questions, I noticed that some of the scores are 0 and -0? May I know why this is the case from Autodock-Vina? Should these scores be treated any differently when doing the evaluation (like not considering them)?
